  
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

homeassistant:
  name: Home
  latitude: !secret homeassistant_latitude
  longitude: !secret homeassistant_longitude
  elevation: !secret homeassistant_elevation
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include_dir_merge_named customize
  packages: !include_dir_named packages
  internal_url: !secret homeassistant_internalurl
  external_url: !secret homeassistant_externalurl
  customize_glob:
    sensor.power_meter_phase3_previous*:
      hidden: true
    sensor.power_meter_phase2_previous*:
      hidden: true
    sensor.power_meter_phase1_previous*:
      hidden: true
    sensor.washer_power_outlet_previous*:
      hidden: true

system_health:

# Text to speech
tts:
  - platform: google_translate

cover:
  - platform: myq
    username: !secret email
    password: !secret cover_myq_password

august:
  login_method: email
  username: !secret email
  password: !secret august_password


zwave:
  usb_path: /dev/ttyUSB0
  network_key: !secret zwave_network_key
  device_config_glob:
    "*_previous*":
      ignored: true
      polling_intensity: 0
#zha:
#  usb_path: /dev/ttyUSB1
#  database_path: /config/zigbee.db

media_player:
  - platform: yamaha_musiccast
    host: 192.168.1.208

zeroconf:

recorder:
  db_url: !secret recorder_db_url
  purge_keep_days: 1
  exclude:
    domains:
      - device_tracker
      - media_player
      - geo_location
      - zwave
      - weather
      - sensor
      - switch
      - media_player
      - binary_sensor
      - light
      - camera
    entities:
      - sun.sun
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_10
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_11
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_12
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_14
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_5
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_6
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_7
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_8
      - sensor.aeon_labs_zw095_home_energy_meter_gen5_previous_reading_9
      - sensor.aeon_labs_zw096_smart_switch_6_previous_reading
      - sensor.aeon_labs_zw096_smart_switch_6_previous_reading_2
      - sensor.power_meter_phase3_previous_reading_15
      - sensor.power_meter_phase1_previous_reading
      - sensor.power_meter_phase1_previous_reading_13
      - sensor.power_meter_phase1_previous_reading_2
      - sensor.power_meter_phase1_previous_reading_3
      - sensor.power_meter_phase1_previous_reading_4
      - sensor.power_meter_phase1_previous_reading_15

ifttt:
  key: !secret ifttt_key

geo_location:
  - platform: usgs_earthquakes_feed
    feed_type: 'past_day_all_earthquakes'
    radius: 500.0

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include_dir_merge_list sensors/

iqvia:
  zip_code: !secret zipcode

# Convert the Wind Direction from degrees to cardinal


camera:
  - platform: badnest
  - platform: local_file
    file_path: /config/images/mail_and_packages/mail_today.gif
    name: mail_usps


frontend:
  themes: !include_dir_merge_named themes
  javascript_version: latest


# Debug Logging
logger:
  default: info
  logs:
    libopenzwave: critical
    openzwave: critical
    homeassistant.components.zwave: critical
    homeassistant.components.websocket_api: warn
    
#  default: info

tuya:
  username : !secret tuya_username
  password: !secret tuya_password
  platform: "smart_life"
  country_code: "1"

wwlln:

badnest:
  user_id: !secret badnest_user_id
  access_token: !secret nest_access_token
  region: us

climate:
  - platform: badnest
    scan_interval: 10

