- platform: nut
  host: 192.168.1.3
  resources:
    - ups.load
    - ups.realpower.nominal
    - input.voltage
    - battery.runtime
    - ups.status
    - battery.charge
    - output.voltage
    - ups.status.display