- platform: template
  sensors:
    allergy_forecast_trend:
      friendly_name: 'Allergy Forecast Trend'
      value_template: '{{ states.sensor.allergy_forecasted_average.attributes.trend }}'
    allergy_forecast_rating:
      friendly_name: 'Allergy Forecast Rating'
      value_template: '{{ states.sensor.allergy_forecasted_average.attributes.rating }}'
    allergy_forecast_outlook:
      friendly_name: 'Allergy Forecast Outlook'
      value_template: '{{ states.sensor.allergy_forecasted_average.attributes.outlook }}'
    allergy_forecast_rating:
      friendly_name: 'Allergy Forecast Season'
      value_template: '{{ states.sensor.allergy_forecasted_average.attributes.season }}'

- platform: template
  sensors:
    friendly_wind_direction:
      friendly_name: 'Wind Direction'
      value_template: >-
          {%if states.sensor.johnson_s_weather_station_wind_dir.state | float<=11 %}N
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float>348 %}N
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=34 | float>11 %}NNE
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=56 | float>34 %}NE
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=79 | float>56 %}ENE
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=101 | float>79 %}E
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=124 | float>101 %}ESE
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=146 | float>124 %}SE
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=169 | float>146 %}SSE
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=191 | float>169 %}S
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=214 | float>191 %}SSW
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=236 | float>214 %}SW
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=259 | float>236 %}WSW
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=281 | float>259 %}W
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=304 | float>281 %}WNW
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=326 | float>304 %}NW
          {% elif states.sensor.johnson_s_weather_station_wind_dir.state | float<=348 | float>326 %}NNW
          {%- endif %}